# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-04 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CleaningDuty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cleaners', models.ManyToManyField(to='webinterface.Cleaner')),
            ],
        ),
        migrations.CreateModel(
            name='CleaningSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cleaners_per_date', models.IntegerField(choices=[(1, 'One'), (2, 'Two')], default=1)),
                ('frequency', models.IntegerField(choices=[(1, 'Every week'), (2, 'Even weeks'), (3, 'Odd weeks')], default=1)),
                ('task1', models.CharField(blank=True, max_length=40)),
                ('task2', models.CharField(blank=True, max_length=40)),
                ('task3', models.CharField(blank=True, max_length=40)),
                ('task4', models.CharField(blank=True, max_length=40)),
                ('task5', models.CharField(blank=True, max_length=40)),
                ('task6', models.CharField(blank=True, max_length=40)),
                ('task7', models.CharField(blank=True, max_length=40)),
                ('task8', models.CharField(blank=True, max_length=40)),
                ('task9', models.CharField(blank=True, max_length=40)),
                ('task10', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='cleaningduty',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webinterface.CleaningSchedule'),
        ),
        migrations.AddField(
            model_name='cleaner',
            name='jobs',
            field=models.ManyToManyField(to='webinterface.CleaningSchedule'),
        ),
    ]
