# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-29 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0002_auto_20171129_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningplan',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
