# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-02 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0003_auto_20171129_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cleaningplan',
            name='task1',
        ),
        migrations.RemoveField(
            model_name='cleaningplan',
            name='task10',
        ),
        migrations.RemoveField(
            model_name='cleaningplan',
            name='task2',
        ),
        migrations.RemoveField(
            model_name='cleaningplan',
            name='task3',
        ),
        migrations.RemoveField(
            model_name='cleaningplan',
            name='task4',
        ),
        migrations.RemoveField(
            model_name='cleaningplan',
            name='task5',
        ),
        migrations.RemoveField(
            model_name='cleaningplan',
            name='task6',
        ),
        migrations.RemoveField(
            model_name='cleaningplan',
            name='task7',
        ),
        migrations.RemoveField(
            model_name='cleaningplan',
            name='task8',
        ),
        migrations.RemoveField(
            model_name='cleaningplan',
            name='task9',
        ),
    ]
