# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-02 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0004_auto_20171202_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaningplan',
            name='task1',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='cleaningplan',
            name='task10',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='cleaningplan',
            name='task2',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='cleaningplan',
            name='task3',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='cleaningplan',
            name='task4',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='cleaningplan',
            name='task5',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='cleaningplan',
            name='task6',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='cleaningplan',
            name='task7',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='cleaningplan',
            name='task8',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='cleaningplan',
            name='task9',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
