# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-03 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0005_auto_20171202_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleaningplan',
            old_name='cleaners_per_week',
            new_name='cleaners_per_date',
        ),
        migrations.RemoveField(
            model_name='cleaners',
            name='email',
        ),
        migrations.AddField(
            model_name='cleaningplan',
            name='frequency',
            field=models.IntegerField(choices=[(1, 'Every week'), (2, 'Even weeks'), (3, 'Odd weeks')], default=1),
        ),
        migrations.AlterField(
            model_name='cleaners',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
