# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-03 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0007_auto_20171203_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('jobs', models.ManyToManyField(to='webinterface.CleaningPlan')),
            ],
        ),
        migrations.DeleteModel(
            name='Cleaners',
        ),
        migrations.AlterField(
            model_name='config',
            name='cleaners',
            field=models.ManyToManyField(to='webinterface.Cleaner'),
        ),
    ]
