# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-04 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0009_cleaningduty_populatedcleaningplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningduty',
            name='cleaner2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaner2', to='webinterface.Cleaner'),
        ),
    ]
