# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-04 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webinterface', '0010_auto_20171204_1343'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CleaningPlan',
            new_name='CleaningSchedule',
        ),
        migrations.RemoveField(
            model_name='config',
            name='cleaners',
        ),
        migrations.RemoveField(
            model_name='config',
            name='cleaning_plans',
        ),
        migrations.RemoveField(
            model_name='populatedcleaningplan',
            name='cleaningplan_ptr',
        ),
        migrations.RemoveField(
            model_name='populatedcleaningplan',
            name='duties',
        ),
        migrations.RemoveField(
            model_name='cleaningduty',
            name='cleaner1',
        ),
        migrations.RemoveField(
            model_name='cleaningduty',
            name='cleaner2',
        ),
        migrations.AddField(
            model_name='cleaningduty',
            name='cleaners',
            field=models.ManyToManyField(to='webinterface.Cleaner'),
        ),
        migrations.AddField(
            model_name='cleaningduty',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webinterface.CleaningSchedule'),
        ),
        migrations.DeleteModel(
            name='Config',
        ),
        migrations.DeleteModel(
            name='PopulatedCleaningPlan',
        ),
    ]
